from .binary_losses import AssumeNegativeLossWithLogits, WeakAssumeNegativeLossWithLogits, BinaryLabelSmoothLossWithLogits, BinaryNegativeLabelSmoothLossWithLogits
from .binary_focal import BinaryFocalLossWithLogits
from .entropy_maximisation import EntropyMaximiseLossWithLogits
